version: '3.8'

services:
  nginx:
    image: ${IMG_SV}
    build:
      context: ./${SV}
    container_name: ${CTNR_SV}
    hostname: ${SV}.${USER}.${DOMAIN}
    ports:
      # - "80:80"
      - "443:443"
      # - "9000:9000"
    networks:
      - my-network
      # - front-net
    # volumes:
      # - sv-conf: /etc/nginx/conf.d
    # env_file:
    #   - ${ENV_FILE}
    depends_on:
      - wordpress
    restart: always

  wordpress:
    image: ${IMG_APP}
    build:
      context: ./${APP}
    container_name: ${CTNR_APP}
    hostname: ${APP}.${USER}.${DOMAIN}
    # environment:
    #   DATABASE_URL: mysql://your_database_user:password@mariadb/your_database_name
    # ports:
      # - "9000:9000"
      # - "3389:3389"
    networks:
      - my-network
      # - front-net
      # - backend-net
    volumes:
      - type: bind
        source: ${DATADIR}/${APP}
        target: /var/www/html
        # persistent: true
        # permissions: rw
      # - app-files:/var/www/html:rw
    env_file:
      - ${ENVFILE}
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: ${IMG_DB}
    build:
      context: ./${DB}
    container_name: ${CTNR_DB}
    hostname: ${DB}.${USER}.${DOMAIN}
    # ports:
      # - "3306:3306"
    networks:
      - my-network
      # - backend-net
    volumes:
      - type: bind
        source: ${DATADIR}/${DB}
        target: /var/lib/mysql
        # persistent: true
        # permissions: rw
      # - db-data:/var/lib/mysql:rw
    # environment:
    #   MYSQL_ROOT_PASSWORD: your_root_password
    #   MYSQL_DATABASE: your_database_name
    #   MYSQL_USER: your_database_user
    #   MYSQL_PASSWORD: your_database_password
    env_file:
      - ${ENVFILE}
    restart: always

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.38.10.0/24
  # front-net:
  #   driver: bridge
  # backend-net:
  #   driver: bridge

# volumes:
#   app-files: ${DATADIR}/{APP}
#   db-data: ${DATADIR}/${DB}
  # sv-conf:
# volumes:
  # app-files:
  #   driver: local
  #   driver_opts:
  #     type: bind
  #     device: ${DATADIR}/${APP}
  # db-data:
  #   driver: local
  #   driver_opts:
  #     type: bind
  #     device: ${DATADIR}/${DB}
