version: '3.8'

services:
  nginx:
    build:
      context: ./srcs/nginx
    container_name: nginx-container
    ports:
      # - "80:80"
      - "443:443"
      # - "9000:9000"
    networks:
      - my-network
      # - front-net
    volumes:
      - wordpress-files:/var/www/html
      - nginx-conf:/etc/nginx/conf.d
    # env_file:
    #   - ./.env
    depends_on:
      - wordpress
    restart: always

  # php-fpm:
  #   build:
  #     context: ./php-fpm
  #   container_name: php-fpm-container
  #   networks:
  #     - my-network
  #   volumes:
  #     - wordpress-files:/var/www/html
  #   depends_on:
  #     - mariadb
  #   restart: always

  wordpress:
    build:
      context: ./srcs/wordpress
    container_name: wordpress-container
    # environment:
    #   DATABASE_URL: mysql://your_database_user:password@mariadb/your_database_name
    # ports:
      # - "9000:9000"
      # - "3389:3389"
    networks:
      - my-network
      # - front-net
      # - backend-net
    volumes:
      - wordpress-files:/home/${USER}/data/wordpress
    env_file:
      - ./.env
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build:
      context: ./srcs/mariadb
    container_name: mariadb-container
    # ports:
      # - "3306:3306"
    networks:
      - my-network
      # - backend-net
    volumes:
      - wordpress-files:/home/${USER}/data/mariadb
    # environment:
    #   MYSQL_ROOT_PASSWORD: your_root_password
    #   MYSQL_DATABASE: your_database_name
    #   MYSQL_USER: your_database_user
    #   MYSQL_PASSWORD: your_database_password
    env_file:
      - ./.env
    restart: always

networks:
  my-network:
    driver: bridge
  # front-net:
  #   driver: bridge
  # backend-net:
  #   driver: bridge

volumes:
  wordpress-files:
  nginx-conf:
  mariadb-data:
